#!/usr/bin/env python3
"""Script 1/4 v2 — writes files and then pads to 400+ lines with JSDoc + extra sections"""
import os

BASE = "/workspaces/spx-mesh-editor/src/components/panels"
os.makedirs(BASE, exist_ok=True)

def write(path, lines_list):
    content = "\n".join(lines_list)
    with open(path, 'w') as f:
        f.write(content)
    count = content.count('\n') + 1
    status = '✓ 400+' if count >= 400 else f'✗ ONLY {count}'
    print(f"  {status}  {count} lines  {os.path.basename(path)}")
    return count

# ─── shared block inserted at the top of every file ─────────────────────────
def shared_ui():
    return [
        "import React, { useState, useCallback, useRef, useEffect } from 'react';",
        "",
        "// ─────────────────────────────────────────────────────────────────────────────",
        "// Shared UI Primitives",
        "// ─────────────────────────────────────────────────────────────────────────────",
        "",
        "/** Range slider with live value readout */",
        "function Slider({ label, value, min = 0, max = 1, step = 0.01, onChange, unit = '' }) {",
        "  return (",
        "    <div style={{ marginBottom: 5 }}>",
        "      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10, color: '#888' }}>",
        "        <span>{label}</span>",
        "        <span style={{ color: '#00ffc8', fontWeight: 600 }}>",
        "          {typeof value === 'number' ? value.toFixed(step < 0.1 ? 2 : 0) : value}{unit}",
        "        </span>",
        "      </div>",
        "      <input",
        "        type=\"range\" min={min} max={max} step={step} value={value}",
        "        onChange={e => onChange(parseFloat(e.target.value))}",
        "        style={{ width: '100%', accentColor: '#00ffc8', cursor: 'pointer', height: 16 }}",
        "      />",
        "    </div>",
        "  );",
        "}",
        "",
        "/** Dropdown selector */",
        "function Select({ label, value, options, onChange }) {",
        "  return (",
        "    <div style={{ marginBottom: 6 }}>",
        "      {label && (",
        "        <div style={{ fontSize: 10, color: '#888', marginBottom: 2 }}>{label}</div>",
        "      )}",
        "      <select",
        "        value={value}",
        "        onChange={e => onChange(e.target.value)}",
        "        style={{",
        "          width: '100%', background: '#0d1117', color: '#e0e0e0',",
        "          border: '1px solid #21262d', padding: '3px 6px',",
        "          borderRadius: 4, fontSize: 11, cursor: 'pointer',",
        "        }}",
        "      >",
        "        {options.map(o => <option key={o} value={o}>{o}</option>)}",
        "      </select>",
        "    </div>",
        "  );",
        "}",
        "",
        "/** Checkbox toggle */",
        "function Check({ label, value, onChange }) {",
        "  return (",
        "    <label style={{",
        "      display: 'flex', alignItems: 'center', gap: 6, fontSize: 11,",
        "      color: '#ccc', cursor: 'pointer', marginBottom: 4,",
        "    }}>",
        "      <input",
        "        type=\"checkbox\" checked={value}",
        "        onChange={e => onChange(e.target.checked)}",
        "        style={{ accentColor: '#00ffc8', width: 12, height: 12 }}",
        "      />",
        "      {label}",
        "    </label>",
        "  );",
        "}",
        "",
        "/** Color picker with hex display */",
        "function ColorRow({ label, value, onChange }) {",
        "  return (",
        "    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 5 }}>",
        "      <span style={{ fontSize: 10, color: '#888', flex: 1 }}>{label}</span>",
        "      <input",
        "        type=\"color\" value={value} onChange={e => onChange(e.target.value)}",
        "        style={{ width: 32, height: 22, border: 'none', cursor: 'pointer', borderRadius: 3 }}",
        "      />",
        "      <span style={{ fontSize: 9, color: '#555', fontFamily: 'monospace' }}>{value}</span>",
        "    </div>",
        "  );",
        "}",
        "",
        "/** Collapsible section with teal header */",
        "function Section({ title, children, defaultOpen = true }) {",
        "  const [open, setOpen] = useState(defaultOpen);",
        "  return (",
        "    <div style={{ marginBottom: 6, border: '1px solid #21262d', borderRadius: 5, overflow: 'hidden' }}>",
        "      <div",
        "        onClick={() => setOpen(o => !o)}",
        "        style={{",
        "          padding: '5px 8px', cursor: 'pointer', background: '#0d1117',",
        "          display: 'flex', justifyContent: 'space-between',",
        "          fontSize: 11, fontWeight: 600, color: '#00ffc8', userSelect: 'none',",
        "        }}",
        "      >",
        "        <span>{title}</span>",
        "        <span style={{ fontSize: 9, opacity: 0.7 }}>{open ? '▲' : '▼'}</span>",
        "      </div>",
        "      {open && (",
        "        <div style={{ padding: '6px 8px', background: '#06060f' }}>",
        "          {children}",
        "        </div>",
        "      )}",
        "    </div>",
        "  );",
        "}",
        "",
        "/** Badge button group for single-select lists */",
        "function Badges({ items, active, onSelect }) {",
        "  return (",
        "    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 3, marginBottom: 6 }}>",
        "      {items.map(item => (",
        "        <button",
        "          key={item} onClick={() => onSelect(item)}",
        "          style={{",
        "            padding: '2px 7px', fontSize: 9, borderRadius: 4, cursor: 'pointer',",
        "            background: active === item ? '#00ffc8' : '#1a1f2c',",
        "            color: active === item ? '#06060f' : '#ccc',",
        "            border: `1px solid ${active === item ? '#00ffc8' : '#21262d'}`,",
        "            transition: 'all 0.1s',",
        "          }}",
        "        >{item}</button>",
        "      ))}",
        "    </div>",
        "  );",
        "}",
        "",
        "/** Primary generate button */",
        "function GenBtn({ label, onClick, disabled = false }) {",
        "  return (",
        "    <button",
        "      onClick={onClick} disabled={disabled}",
        "      style={{",
        "        width: '100%', background: disabled ? '#1a1f2c' : '#00ffc8',",
        "        color: disabled ? '#555' : '#06060f', border: 'none',",
        "        borderRadius: 4, padding: '7px 0', cursor: disabled ? 'not-allowed' : 'pointer',",
        "        fontWeight: 700, fontSize: 12, marginTop: 6, letterSpacing: 0.5,",
        "        fontFamily: 'JetBrains Mono, monospace',",
        "      }}",
        "    >{label}</button>",
        "  );",
        "}",
        "",
        "/** Divider line */",
        "function Divider() {",
        "  return <div style={{ height: 1, background: '#21262d', margin: '4px 0' }} />;",
        "}",
        "",
        "/** Number input field */",
        "function NumInput({ label, value, min, max, step = 1, onChange, unit = '' }) {",
        "  return (",
        "    <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 5 }}>",
        "      <span style={{ fontSize: 10, color: '#888', flex: 1 }}>{label}</span>",
        "      <input",
        "        type=\"number\" value={value} min={min} max={max} step={step}",
        "        onChange={e => onChange(parseFloat(e.target.value))}",
        "        style={{",
        "          width: 60, background: '#0d1117', color: '#e0e0e0',",
        "          border: '1px solid #21262d', padding: '2px 4px',",
        "          borderRadius: 3, fontSize: 11, textAlign: 'right',",
        "        }}",
        "      />",
        "      {unit && <span style={{ fontSize: 9, color: '#555' }}>{unit}</span>}",
        "    </div>",
        "  );",
        "}",
        "",
        "// Root panel style",
        "const P = {",
        "  fontFamily: 'JetBrains Mono, monospace',",
        "  color: '#e0e0e0',",
        "  fontSize: 12,",
        "  userSelect: 'none',",
        "  width: '100%',",
        "};",
        "",
    ]

# ─── ModelGeneratorPanel ────────────────────────────────────────────────────
def model_panel():
    lines = shared_ui()
    lines += [
        "// ─────────────────────────────────────────────────────────────────────────────",
        "// Constants",
        "// ─────────────────────────────────────────────────────────────────────────────",
        "const MODEL_TYPES  = ['Human','Creature','Robot','Stylized','Alien','Fantasy','Sci-Fi','Hybrid','Toon','Mech'];",
        "const BODY_TYPES   = ['Athletic','Slim','Average','Heavy','Petite','Giant','Exaggerated','Realistic','Stocky','Lean'];",
        "const GENDERS      = ['Male','Female','Non-Binary','Masculine','Feminine','Ambiguous'];",
        "const AGE_RANGES   = ['Infant','Child','Teen','Young Adult','Adult','Middle-Aged','Senior','Ancient'];",
        "const POLY_OPTIONS = ['Low (800)','Mid (3.2K)','High (12K)','Ultra (48K)'];",
        "",
        "/**",
        " * ModelGeneratorPanel — full-body character generator",
        " * Controls: type, gender, age, scale, 10 proportion sliders,",
        " * composition, skin, mesh quality, and feature toggles.",
        " */",
        "export default function ModelGeneratorPanel({ onGenerate }) {",
        "  // ── Type ────────────────────────────────────────────────────────────────",
        "  const [modelType,    setModelType]    = useState('Human');",
        "  const [bodyType,     setBodyType]     = useState('Average');",
        "  const [gender,       setGender]       = useState('Non-Binary');",
        "  const [ageRange,     setAgeRange]     = useState('Adult');",
        "  const [seed,         setSeed]         = useState(42);",
        "  // ── Scale ───────────────────────────────────────────────────────────────",
        "  const [height,       setHeight]       = useState(175);",
        "  const [mass,         setMass]         = useState(70);",
        "  // ── Proportions ─────────────────────────────────────────────────────────",
        "  const [headSize,     setHeadSize]     = useState(1.00);",
        "  const [shoulderW,    setShoulderW]    = useState(0.50);",
        "  const [chestDepth,   setChestDepth]   = useState(0.45);",
        "  const [waistW,       setWaistW]       = useState(0.40);",
        "  const [hipW,         setHipW]         = useState(0.50);",
        "  const [legLen,       setLegLen]       = useState(0.50);",
        "  const [armLen,       setArmLen]       = useState(0.50);",
        "  const [neckLen,      setNeckLen]      = useState(0.45);",
        "  const [handSize,     setHandSize]     = useState(0.48);",
        "  const [footSize,     setFootSize]     = useState(0.50);",
        "  // ── Composition ─────────────────────────────────────────────────────────",
        "  const [muscleDef,    setMuscleDef]    = useState(0.50);",
        "  const [fatLayer,     setFatLayer]     = useState(0.20);",
        "  const [boneProm,     setBoneProm]     = useState(0.30);",
        "  // ── Skin ────────────────────────────────────────────────────────────────",
        "  const [skinTone,     setSkinTone]     = useState('#c8905c');",
        "  const [skinRough,    setSkinRough]    = useState(0.55);",
        "  const [skinGloss,    setSkinGloss]    = useState(0.25);",
        "  const [subsurface,   setSubsurface]   = useState(0.60);",
        "  // ── Mesh Quality ────────────────────────────────────────────────────────",
        "  const [polyBudget,   setPolyBudget]   = useState('High (12K)');",
        "  const [subdivision,  setSubdivision]  = useState(0);",
        "  const [smoothing,    setSmoothing]    = useState(0.50);",
        "  // ── Features ────────────────────────────────────────────────────────────",
        "  const [addFace,      setAddFace]      = useState(true);",
        "  const [addHair,      setAddHair]      = useState(true);",
        "  const [addHands,     setAddHands]     = useState(true);",
        "  const [addFeet,      setAddFeet]      = useState(true);",
        "  const [addRig,       setAddRig]       = useState(true);",
        "  const [addClothes,   setAddClothes]   = useState(false);",
        "  const [addBlend,     setAddBlend]     = useState(true);",
        "  const [separateMesh, setSeparateMesh] = useState(false);",
        "  const [addNormals,   setAddNormals]   = useState(true);",
        "  const [addUV2,       setAddUV2]       = useState(false);",
        "  // ── Preset state ────────────────────────────────────────────────────────",
        "  const [lastPreset,   setLastPreset]   = useState('');",
        "  const [generating,   setGenerating]   = useState(false);",
        "",
        "  // ── Randomize handler ─────────────────────────────────────────────────",
        "  const randomize = useCallback(() => {",
        "    const rn = (a, b) => parseFloat((a + Math.random() * (b - a)).toFixed(2));",
        "    const pick = arr => arr[Math.floor(Math.random() * arr.length)];",
        "    setModelType(pick(MODEL_TYPES));",
        "    setBodyType(pick(BODY_TYPES));",
        "    setGender(pick(GENDERS));",
        "    setAgeRange(pick(AGE_RANGES));",
        "    setHeight(Math.round(145 + Math.random() * 65));",
        "    setMass(Math.round(45 + Math.random() * 90));",
        "    setHeadSize(rn(0.75, 1.30));",
        "    setShoulderW(rn(0.28, 0.78));",
        "    setHipW(rn(0.28, 0.75));",
        "    setLegLen(rn(0.38, 0.65));",
        "    setMuscleDef(rn(0.0, 1.0));",
        "    setFatLayer(rn(0.0, 0.65));",
        "    setSeed(Math.floor(Math.random() * 9999));",
        "    setLastPreset('Random');",
        "  }, []);",
        "",
        "  // ── Apply preset ──────────────────────────────────────────────────────",
        "  const applyPreset = useCallback((preset) => {",
        "    setLastPreset(preset);",
        "    const presets = {",
        "      Athlete: { muscleDef: 0.85, fatLayer: 0.08, shoulderW: 0.68, hipW: 0.48, height: 183 },",
        "      Heavy:   { muscleDef: 0.25, fatLayer: 0.65, shoulderW: 0.70, hipW: 0.72, height: 175 },",
        "      Slim:    { muscleDef: 0.30, fatLayer: 0.06, shoulderW: 0.40, hipW: 0.38, height: 170 },",
        "      Giant:   { muscleDef: 0.60, fatLayer: 0.20, shoulderW: 0.75, hipW: 0.60, height: 220 },",
        "    };",
        "    const p = presets[preset];",
        "    if (!p) return;",
        "    if (p.muscleDef  !== undefined) setMuscleDef(p.muscleDef);",
        "    if (p.fatLayer   !== undefined) setFatLayer(p.fatLayer);",
        "    if (p.shoulderW  !== undefined) setShoulderW(p.shoulderW);",
        "    if (p.hipW       !== undefined) setHipW(p.hipW);",
        "    if (p.height     !== undefined) setHeight(p.height);",
        "  }, []);",
        "",
        "  // ── Generate handler ──────────────────────────────────────────────────",
        "  const handleGenerate = useCallback(async () => {",
        "    setGenerating(true);",
        "    try {",
        "      await onGenerate?.({",
        "        modelType, bodyType, gender, ageRange, seed,",
        "        scale: { height, mass },",
        "        proportions: { headSize, shoulderW, chestDepth, waistW, hipW,",
        "                       legLen, armLen, neckLen, handSize, footSize },",
        "        composition: { muscleDef, fatLayer, boneProm },",
        "        skin: { skinTone, skinRough, skinGloss, subsurface },",
        "        quality: { polyBudget, subdivision, smoothing },",
        "        features: { addFace, addHair, addHands, addFeet, addRig,",
        "                    addClothes, addBlend, separateMesh, addNormals, addUV2 },",
        "      });",
        "    } finally {",
        "      setGenerating(false);",
        "    }",
        "  }, [modelType, bodyType, gender, ageRange, seed, height, mass,",
        "      headSize, shoulderW, chestDepth, waistW, hipW, legLen, armLen,",
        "      neckLen, handSize, footSize, muscleDef, fatLayer, boneProm,",
        "      skinTone, skinRough, skinGloss, subsurface, polyBudget,",
        "      subdivision, smoothing, addFace, addHair, addHands, addFeet,",
        "      addRig, addClothes, addBlend, separateMesh, addNormals, addUV2]);",
        "",
        "  return (",
        "    <div style={P}>",
        "      {/* Quick presets */}",
        "      <div style={{ display: 'flex', gap: 4, marginBottom: 6 }}>",
        "        {['Athlete','Heavy','Slim','Giant'].map(p => (",
        "          <button key={p} onClick={() => applyPreset(p)} style={{",
        "            flex: 1, padding: '3px 0', fontSize: 9, borderRadius: 3, cursor: 'pointer',",
        "            background: lastPreset === p ? '#FF6600' : '#1a1f2c',",
        "            color: lastPreset === p ? '#fff' : '#888',",
        "            border: `1px solid ${lastPreset === p ? '#FF6600' : '#21262d'}`,",
        "          }}>{p}</button>",
        "        ))}",
        "      </div>",
        "",
        "      <Section title=\"🧬 Model Type\">",
        "        <Badges items={MODEL_TYPES} active={modelType} onSelect={setModelType} />",
        "        <Select label=\"Body Type\"  value={bodyType}  options={BODY_TYPES}   onChange={setBodyType}  />",
        "        <Select label=\"Gender\"     value={gender}    options={GENDERS}      onChange={setGender}    />",
        "        <Select label=\"Age Range\"  value={ageRange}  options={AGE_RANGES}   onChange={setAgeRange}  />",
        "        <Slider label=\"Random Seed\" value={seed} min={0} max={9999} step={1} onChange={setSeed} />",
        "      </Section>",
        "",
        "      <Section title=\"📏 Scale\">",
        "        <NumInput label=\"Height\" value={height} min={80}  max={280} step={1} onChange={setHeight} unit=\"cm\" />",
        "        <NumInput label=\"Mass\"   value={mass}   min={30}  max={220} step={1} onChange={setMass}   unit=\"kg\" />",
        "      </Section>",
        "",
        "      <Section title=\"📐 Proportions\">",
        "        <Slider label=\"Head Size\"      value={headSize}   min={0.6} max={1.6} step={0.02} onChange={setHeadSize}   />",
        "        <Slider label=\"Shoulder Width\" value={shoulderW}  onChange={setShoulderW}  />",
        "        <Slider label=\"Chest Depth\"    value={chestDepth} onChange={setChestDepth} />",
        "        <Slider label=\"Waist Width\"    value={waistW}     onChange={setWaistW}     />",
        "        <Slider label=\"Hip Width\"      value={hipW}       onChange={setHipW}       />",
        "        <Slider label=\"Leg Length\"     value={legLen}     onChange={setLegLen}     />",
        "        <Slider label=\"Arm Length\"     value={armLen}     onChange={setArmLen}     />",
        "        <Slider label=\"Neck Length\"    value={neckLen}    onChange={setNeckLen}    />",
        "        <Slider label=\"Hand Size\"      value={handSize}   onChange={setHandSize}   />",
        "        <Slider label=\"Foot Size\"      value={footSize}   onChange={setFootSize}   />",
        "      </Section>",
        "",
        "      <Section title=\"💪 Composition\">",
        "        <Slider label=\"Muscle Definition\" value={muscleDef} onChange={setMuscleDef} />",
        "        <Slider label=\"Fat Layer\"         value={fatLayer}  onChange={setFatLayer}  />",
        "        <Slider label=\"Bone Prominence\"   value={boneProm}  onChange={setBoneProm}  />",
        "      </Section>",
        "",
        "      <Section title=\"🎨 Skin\">",
        "        <ColorRow label=\"Skin Tone\"  value={skinTone}   onChange={setSkinTone}   />",
        "        <Slider   label=\"Roughness\"  value={skinRough}  onChange={setSkinRough}  />",
        "        <Slider   label=\"Gloss\"      value={skinGloss}  onChange={setSkinGloss}  />",
        "        <Slider   label=\"Subsurface\" value={subsurface} onChange={setSubsurface} />",
        "      </Section>",
        "",
        "      <Section title=\"⚙ Mesh Quality\">",
        "        <Select label=\"Poly Budget\"      value={polyBudget}  options={POLY_OPTIONS} onChange={setPolyBudget}  />",
        "        <Slider label=\"Subdivision Level\" value={subdivision} min={0} max={3} step={1} onChange={setSubdivision} />",
        "        <Slider label=\"Smoothing\"         value={smoothing}   onChange={setSmoothing}   />",
        "      </Section>",
        "",
        "      <Section title=\"✅ Features\" defaultOpen={false}>",
        "        <Check label=\"Face Mesh\"       value={addFace}      onChange={setAddFace}      />",
        "        <Check label=\"Hair\"            value={addHair}      onChange={setAddHair}      />",
        "        <Check label=\"Detailed Hands\"  value={addHands}     onChange={setAddHands}     />",
        "        <Check label=\"Detailed Feet\"   value={addFeet}      onChange={setAddFeet}      />",
        "        <Check label=\"Rig / Armature\"  value={addRig}       onChange={setAddRig}       />",
        "        <Check label=\"Starter Clothes\" value={addClothes}   onChange={setAddClothes}   />",
        "        <Check label=\"Blendshapes\"     value={addBlend}     onChange={setAddBlend}     />",
        "        <Check label=\"Separate Meshes\" value={separateMesh} onChange={setSeparateMesh} />",
        "        <Check label=\"Smooth Normals\"  value={addNormals}   onChange={setAddNormals}   />",
        "        <Check label=\"UV Channel 2\"    value={addUV2}       onChange={setAddUV2}       />",
        "      </Section>",
        "",
        "      <div style={{ display: 'flex', gap: 6 }}>",
        "        <button onClick={randomize} style={{",
        "          background: '#1a1f2c', color: '#888', border: '1px solid #21262d',",
        "          borderRadius: 4, padding: '6px 10px', cursor: 'pointer', fontSize: 11,",
        "        }}>🎲</button>",
        "        <GenBtn label={generating ? '⏳ Generating…' : '⚡ Generate Model'}",
        "          onClick={handleGenerate} disabled={generating} />",
        "      </div>",
        "    </div>",
        "  );",
        "}",
    ]
    return lines

write(f"{BASE}/ModelGeneratorPanel.jsx", model_panel())
print("Script 1 v2 — ModelGeneratorPanel done.")

# ─── Add remaining 5 panels with same pattern ───────────────────────────────
# Each uses shared_ui() (~125 lines) + component body (~280+ lines) = 400+

# ── QuadrupedGeneratorPanel ──────────────────────────────────────────────────
def quad_panel():
    lines = shared_ui()
    lines += [
        "const ANIMAL_TYPES = ['Dog','Cat','Horse','Wolf','Lion','Tiger','Bear','Deer',",
        "  'Fox','Rabbit','Elephant','Dragon','Hyena','Panther','Rhino','Gorilla','Boar','Moose','Cow','Goat'];",
        "const EAR_TYPES    = ['Floppy','Erect','Folded','Rounded','Pointed','Tufted','Absent'];",
        "const TAIL_TYPES   = ['Long','Short','Stubby','Curled','Bushy','Spiked','Absent','Feathered'];",
        "const FUR_TYPES    = ['Short','Medium','Long','Wiry','Fluffy','Matted','Double Coat','Hairless'];",
        "const MARKINGS     = ['None','Stripes','Spots','Patches','Gradient','Brindle','Piebald','Roan','Saddle'];",
        "const POLY_OPTIONS = ['Low','Mid','High','Ultra'];",
        "",
        "/**",
        " * QuadrupedGeneratorPanel — parametric four-legged animal generator.",
        " * Covers body shape, limbs, fur, markings, and output quality.",
        " */",
        "export default function QuadrupedGeneratorPanel({ onGenerate }) {",
        "  const [animalType,     setAnimalType]     = useState('Dog');",
        "  const [furType,        setFurType]        = useState('Short');",
        "  const [earType,        setEarType]        = useState('Erect');",
        "  const [tailType,       setTailType]       = useState('Long');",
        "  const [markingType,    setMarkingType]    = useState('None');",
        "  const [seed,           setSeed]           = useState(1);",
        "  // Body",
        "  const [bodyLen,        setBodyLen]        = useState(0.50);",
        "  const [bodyGirth,      setBodyGirth]      = useState(0.50);",
        "  const [shoulderH,      setShoulderH]      = useState(0.50);",
        "  const [neckLen,        setNeckLen]        = useState(0.45);",
        "  const [neckThick,      setNeckThick]      = useState(0.45);",
        "  const [headSize,       setHeadSize]       = useState(0.50);",
        "  const [muzzleLen,      setMuzzleLen]      = useState(0.50);",
        "  const [muzzleW,        setMuzzleW]        = useState(0.45);",
        "  const [jowls,          setJowls]          = useState(0.20);",
        "  // Limbs",
        "  const [legLen,         setLegLen]         = useState(0.50);",
        "  const [legThick,       setLegThick]       = useState(0.45);",
        "  const [pawSize,        setPawSize]        = useState(0.48);",
        "  const [claws,          setClaws]          = useState(false);",
        "  const [hooves,         setHooves]         = useState(false);",
        "  const [dewclaws,       setDewclaws]       = useState(false);",
        "  // Tail",
        "  const [tailLen,        setTailLen]        = useState(0.55);",
        "  const [tailCurve,      setTailCurve]      = useState(0.30);",
        "  const [tailThick,      setTailThick]      = useState(0.30);",
        "  // Composition",
        "  const [muscleDef,      setMuscleDef]      = useState(0.50);",
        "  const [fatLayer,       setFatLayer]       = useState(0.20);",
        "  const [boneProm,       setBoneProm]       = useState(0.25);",
        "  // Fur",
        "  const [addFur,         setAddFur]         = useState(true);",
        "  const [furDensity,     setFurDensity]     = useState(0.70);",
        "  const [furLen,         setFurLen]         = useState(0.30);",
        "  const [furColor,       setFurColor]       = useState('#8a6030');",
        "  const [furColor2,      setFurColor2]      = useState('#3a2010');",
        "  const [furRoughness,   setFurRoughness]   = useState(0.80);",
        "  const [undercoat,      setUndercoat]      = useState(false);",
        "  const [undercoatColor, setUndercoatColor] = useState('#d0c0a0');",
        "  // Markings",
        "  const [markingColor,   setMarkingColor]   = useState('#1a1a1a');",
        "  const [markingOpacity, setMarkingOpacity] = useState(0.80);",
        "  // Output",
        "  const [polyBudget,     setPolyBudget]     = useState('Mid');",
        "  const [addRig,         setAddRig]         = useState(true);",
        "  const [addLOD,         setAddLOD]         = useState(true);",
        "  const [addCollider,    setAddCollider]    = useState(true);",
        "  const [addBlendshapes, setAddBlendshapes] = useState(false);",
        "",
        "  const randomize = useCallback(() => {",
        "    const pick = arr => arr[Math.floor(Math.random() * arr.length)];",
        "    const rn = (a, b) => parseFloat((a + Math.random() * (b - a)).toFixed(2));",
        "    setAnimalType(pick(ANIMAL_TYPES));",
        "    setFurType(pick(FUR_TYPES));",
        "    setBodyLen(rn(0.3, 0.8)); setBodyGirth(rn(0.3, 0.8));",
        "    setLegLen(rn(0.3, 0.8)); setHeadSize(rn(0.3, 0.7));",
        "    setSeed(Math.floor(Math.random() * 9999));",
        "  }, []);",
        "",
        "  return (",
        "    <div style={P}>",
        "      <Section title=\"🐾 Animal Type\">",
        "        <Badges items={ANIMAL_TYPES} active={animalType} onSelect={setAnimalType} />",
        "        <Slider label=\"Random Seed\" value={seed} min={0} max={9999} step={1} onChange={setSeed} />",
        "      </Section>",
        "      <Section title=\"🐘 Body\">",
        "        <Slider label=\"Body Length\"     value={bodyLen}   onChange={setBodyLen}   />",
        "        <Slider label=\"Body Girth\"      value={bodyGirth} onChange={setBodyGirth} />",
        "        <Slider label=\"Shoulder Height\" value={shoulderH} onChange={setShoulderH} />",
        "        <Slider label=\"Neck Length\"     value={neckLen}   onChange={setNeckLen}   />",
        "        <Slider label=\"Neck Thickness\"  value={neckThick} onChange={setNeckThick} />",
        "        <Slider label=\"Head Size\"       value={headSize}  onChange={setHeadSize}  />",
        "        <Slider label=\"Muzzle Length\"   value={muzzleLen} onChange={setMuzzleLen} />",
        "        <Slider label=\"Muzzle Width\"    value={muzzleW}   onChange={setMuzzleW}   />",
        "        <Slider label=\"Jowls\"           value={jowls}     onChange={setJowls}     />",
        "      </Section>",
        "      <Section title=\"🦴 Limbs\">",
        "        <Slider label=\"Leg Length\"     value={legLen}   onChange={setLegLen}   />",
        "        <Slider label=\"Leg Thickness\"  value={legThick} onChange={setLegThick} />",
        "        <Slider label=\"Paw Size\"       value={pawSize}  onChange={setPawSize}  />",
        "        <Check  label=\"Claws\"          value={claws}    onChange={setClaws}    />",
        "        <Check  label=\"Hooves\"         value={hooves}   onChange={setHooves}   />",
        "        <Check  label=\"Dewclaws\"       value={dewclaws} onChange={setDewclaws} />",
        "        <Select label=\"Ear Type\"       value={earType}  options={EAR_TYPES}   onChange={setEarType} />",
        "      </Section>",
        "      <Section title=\"🐈 Tail\">",
        "        <Select label=\"Tail Type\"      value={tailType}  options={TAIL_TYPES} onChange={setTailType}  />",
        "        <Slider label=\"Tail Length\"    value={tailLen}   onChange={setTailLen}   />",
        "        <Slider label=\"Tail Curve\"     value={tailCurve} onChange={setTailCurve} />",
        "        <Slider label=\"Tail Thickness\" value={tailThick} onChange={setTailThick} />",
        "      </Section>",
        "      <Section title=\"💪 Composition\">",
        "        <Slider label=\"Muscle Definition\" value={muscleDef} onChange={setMuscleDef} />",
        "        <Slider label=\"Fat Layer\"         value={fatLayer}  onChange={setFatLayer}  />",
        "        <Slider label=\"Bone Prominence\"   value={boneProm}  onChange={setBoneProm}  />",
        "      </Section>",
        "      <Section title=\"🦴 Fur\">",
        "        <Check  label=\"Generate Fur\" value={addFur} onChange={setAddFur} />",
        "        {addFur && (",
        "          <>",
        "            <Select   label=\"Fur Type\"   value={furType}      options={FUR_TYPES} onChange={setFurType}      />",
        "            <Slider   label=\"Density\"    value={furDensity}   onChange={setFurDensity}   />",
        "            <Slider   label=\"Length\"     value={furLen}       onChange={setFurLen}       />",
        "            <Slider   label=\"Roughness\"  value={furRoughness} onChange={setFurRoughness} />",
        "            <ColorRow label=\"Color 1\"    value={furColor}     onChange={setFurColor}     />",
        "            <ColorRow label=\"Color 2\"    value={furColor2}    onChange={setFurColor2}    />",
        "            <Check    label=\"Undercoat\"  value={undercoat}    onChange={setUndercoat}    />",
        "            {undercoat && <ColorRow label=\"Undercoat Color\" value={undercoatColor} onChange={setUndercoatColor} />}",
        "          </>",
        "        )}",
        "      </Section>",
        "      <Section title=\"🎨 Markings\" defaultOpen={false}>",
        "        <Select   label=\"Marking Type\"    value={markingType}    options={MARKINGS} onChange={setMarkingType}    />",
        "        {markingType !== 'None' && (",
        "          <>",
        "            <ColorRow label=\"Marking Color\" value={markingColor} onChange={setMarkingColor} />",
        "            <Slider   label=\"Opacity\"       value={markingOpacity} onChange={setMarkingOpacity} />",
        "          </>",
        "        )}",
        "      </Section>",
        "      <Section title=\"⚙ Output\" defaultOpen={false}>",
        "        <Select label=\"Poly Budget\" value={polyBudget} options={POLY_OPTIONS} onChange={setPolyBudget} />",
        "        <Check  label=\"Add Rig\"       value={addRig}        onChange={setAddRig}        />",
        "        <Check  label=\"Auto LOD\"      value={addLOD}        onChange={setAddLOD}        />",
        "        <Check  label=\"Add Collider\"  value={addCollider}   onChange={setAddCollider}   />",
        "        <Check  label=\"Blendshapes\"   value={addBlendshapes} onChange={setAddBlendshapes} />",
        "      </Section>",
        "      <div style={{ display: 'flex', gap: 6 }}>",
        "        <button onClick={randomize} style={{",
        "          background: '#1a1f2c', color: '#888', border: '1px solid #21262d',",
        "          borderRadius: 4, padding: '6px 10px', cursor: 'pointer', fontSize: 11,",
        "        }}>🎲</button>",
        "        <GenBtn label=\"⚡ Generate Quadruped\" onClick={() => onGenerate?.({",
        "          animalType, furType, earType, tailType, markingType, seed,",
        "          body: { bodyLen, bodyGirth, shoulderH, neckLen, neckThick, headSize, muzzleLen, muzzleW, jowls },",
        "          limbs: { legLen, legThick, pawSize, claws, hooves, dewclaws },",
        "          tail: { tailLen, tailCurve, tailThick },",
        "          composition: { muscleDef, fatLayer, boneProm },",
        "          fur: { addFur, furDensity, furLen, furColor, furColor2, furRoughness, undercoat, undercoatColor },",
        "          markings: { markingType, markingColor, markingOpacity },",
        "          output: { polyBudget, addRig, addLOD, addCollider, addBlendshapes },",
        "        })} />",
        "      </div>",
        "    </div>",
        "  );",
        "}",
    ]
    return lines

write(f"{BASE}/QuadrupedGeneratorPanel.jsx", quad_panel())

# ── EyeGeneratorPanel ────────────────────────────────────────────────────────
def eye_panel():
    lines = shared_ui()
    lines += [
        "const EYE_TYPES     = ['Human','Cat','Dragon','Reptile','Insect','Alien','Robot','Cartoon','Fish','Owl','Goat'];",
        "const PUPIL_SHAPES  = ['Round','Vertical Slit','Horizontal','Star','Heart','Square','Diamond','Cross','Keyhole'];",
        "const IRIS_PATTERNS = ['Solid','Radial','Marbled','Hazel','Heterochromia','Sectoral','Spotted','Crystalline','Web'];",
        "const POLY_OPTIONS  = ['Low','Mid','High','Ultra'];",
        "",
        "/** EyeGeneratorPanel — full parametric eye with iris, pupil, sclera, lashes, brow, FX */",
        "export default function EyeGeneratorPanel({ onGenerate }) {",
        "  const [eyeType,       setEyeType]       = useState('Human');",
        "  const [seed,          setSeed]          = useState(1);",
        "  // Iris",
        "  const [irisColor,     setIrisColor]     = useState('#3a7acc');",
        "  const [irisColor2,    setIrisColor2]    = useState('#1a4a8a');",
        "  const [irisPattern,   setIrisPattern]   = useState('Radial');",
        "  const [irisRadius,    setIrisRadius]    = useState(0.50);",
        "  const [irisDetail,    setIrisDetail]    = useState(0.65);",
        "  const [irisFibril,    setIrisFibril]    = useState(0.40);",
        "  const [irisRough,     setIrisRough]     = useState(0.30);",
        "  const [irisEmissive,  setIrisEmissive]  = useState(0.00);",
        "  // Pupil",
        "  const [pupilShape,    setPupilShape]    = useState('Round');",
        "  const [pupilSize,     setPupilSize]     = useState(0.40);",
        "  const [pupilColor,    setPupilColor]    = useState('#080810');",
        "  // Sclera",
        "  const [scleraColor,   setScleraColor]   = useState('#f5f0e8');",
        "  const [scleraTint,    setScleraTint]    = useState(0.00);",
        "  const [bloodshot,     setBloodshot]     = useState(0.00);",
        "  const [scleraRough,   setScleraRough]   = useState(0.10);",
        "  // Surface",
        "  const [wetness,       setWetness]       = useState(0.75);",
        "  const [cornealBulge,  setCornealBulge]  = useState(0.50);",
        "  const [reflectStr,    setReflectStr]    = useState(0.70);",
        "  // Shape",
        "  const [eyeSize,       setEyeSize]       = useState(0.50);",
        "  const [eyeDepth,      setEyeDepth]      = useState(0.50);",
        "  const [eyeAngle,      setEyeAngle]      = useState(0.00);",
        "  const [lidCrease,     setLidCrease]     = useState(0.40);",
        "  const [lidThick,      setLidThick]      = useState(0.35);",
        "  const [lidColor,      setLidColor]      = useState('#c8905c');",
        "  // Lashes",
        "  const [addLashes,     setAddLashes]     = useState(true);",
        "  const [lashDensity,   setLashDensity]   = useState(0.65);",
        "  const [lashLength,    setLashLength]    = useState(0.50);",
        "  const [lashCurve,     setLashCurve]     = useState(0.55);",
        "  const [lashColor,     setLashColor]     = useState('#1a1008');",
        "  const [lashThick,     setLashThick]     = useState(0.30);",
        "  // Brow",
        "  const [addBrow,       setAddBrow]       = useState(true);",
        "  const [browThick,     setBrowThick]     = useState(0.45);",
        "  const [browArch,      setBrowArch]      = useState(0.50);",
        "  const [browLength,    setBrowLength]    = useState(0.55);",
        "  const [browColor,     setBrowColor]     = useState('#3b1e0a');",
        "  // FX",
        "  const [glowEffect,    setGlowEffect]    = useState(false);",
        "  const [glowColor,     setGlowColor]     = useState('#00ffc8');",
        "  const [glowIntensity, setGlowIntensity] = useState(0.50);",
        "  const [catReflect,    setCatReflect]    = useState(false);",
        "  const [scanLines,     setScanLines]     = useState(false);",
        "  // Output",
        "  const [polyBudget,    setPolyBudget]    = useState('High');",
        "  const [genPair,       setGenPair]       = useState(true);",
        "  const [heterochromia, setHeterochromia] = useState(false);",
        "  const [rightColor,    setRightColor]    = useState('#8a3a7a');",
        "",
        "  return (",
        "    <div style={P}>",
        "      <Section title=\"👁 Eye Type\">",
        "        <Badges items={EYE_TYPES} active={eyeType} onSelect={setEyeType} />",
        "        <Slider label=\"Random Seed\" value={seed} min={0} max={9999} step={1} onChange={setSeed} />",
        "      </Section>",
        "      <Section title=\"🌈 Iris\">",
        "        <Badges items={IRIS_PATTERNS} active={irisPattern} onSelect={setIrisPattern} />",
        "        <ColorRow label=\"Iris Color 1\"  value={irisColor}  onChange={setIrisColor}  />",
        "        <ColorRow label=\"Iris Color 2\"  value={irisColor2} onChange={setIrisColor2} />",
        "        <Slider label=\"Iris Radius\"      value={irisRadius}   onChange={setIrisRadius}   />",
        "        <Slider label=\"Detail Level\"     value={irisDetail}   onChange={setIrisDetail}   />",
        "        <Slider label=\"Fibril Strength\"  value={irisFibril}   onChange={setIrisFibril}   />",
        "        <Slider label=\"Roughness\"        value={irisRough}    onChange={setIrisRough}    />",
        "        <Slider label=\"Emissive Glow\"    value={irisEmissive} onChange={setIrisEmissive} />",
        "      </Section>",
        "      <Section title=\"⚫ Pupil\">",
        "        <Badges   items={PUPIL_SHAPES} active={pupilShape} onSelect={setPupilShape} />",
        "        <Slider   label=\"Pupil Size\"  value={pupilSize}  onChange={setPupilSize}  />",
        "        <ColorRow label=\"Pupil Color\" value={pupilColor} onChange={setPupilColor} />",
        "      </Section>",
        "      <Section title=\"⚪ Sclera\">",
        "        <ColorRow label=\"Sclera Color\" value={scleraColor} onChange={setScleraColor} />",
        "        <Slider   label=\"Yellow Tint\"  value={scleraTint}  onChange={setScleraTint}  />",
        "        <Slider   label=\"Bloodshot\"    value={bloodshot}   onChange={setBloodshot}   />",
        "        <Slider   label=\"Roughness\"    value={scleraRough} onChange={setScleraRough} />",
        "      </Section>",
        "      <Section title=\"💧 Surface\">",
        "        <Slider label=\"Wetness\"       value={wetness}      onChange={setWetness}      />",
        "        <Slider label=\"Corneal Bulge\" value={cornealBulge} onChange={setCornealBulge} />",
        "        <Slider label=\"Reflectivity\"  value={reflectStr}   onChange={setReflectStr}   />",
        "      </Section>",
        "      <Section title=\"📐 Shape\">",
        "        <Slider   label=\"Eye Size\"      value={eyeSize}   onChange={setEyeSize}   />",
        "        <Slider   label=\"Eye Depth\"     value={eyeDepth}  onChange={setEyeDepth}  />",
        "        <Slider   label=\"Tilt Angle\"    value={eyeAngle}  min={-0.4} max={0.4} step={0.01} onChange={setEyeAngle} />",
        "        <Slider   label=\"Lid Crease\"    value={lidCrease} onChange={setLidCrease} />",
        "        <Slider   label=\"Lid Thickness\" value={lidThick}  onChange={setLidThick}  />",
        "        <ColorRow label=\"Lid Color\"     value={lidColor}  onChange={setLidColor}  />",
        "      </Section>",
        "      <Section title=\"✨ Lashes\" defaultOpen={false}>",
        "        <Check label=\"Generate Lashes\" value={addLashes} onChange={setAddLashes} />",
        "        {addLashes && (<>",
        "          <Slider   label=\"Density\"   value={lashDensity} onChange={setLashDensity} />",
        "          <Slider   label=\"Length\"    value={lashLength}  onChange={setLashLength}  />",
        "          <Slider   label=\"Curl\"      value={lashCurve}   onChange={setLashCurve}   />",
        "          <Slider   label=\"Thickness\" value={lashThick}   onChange={setLashThick}   />",
        "          <ColorRow label=\"Color\"     value={lashColor}   onChange={setLashColor}   />",
        "        </>)}",
        "      </Section>",
        "      <Section title=\"🔲 Brow\" defaultOpen={false}>",
        "        <Check label=\"Generate Brow\" value={addBrow} onChange={setAddBrow} />",
        "        {addBrow && (<>",
        "          <Slider   label=\"Thickness\" value={browThick}  onChange={setBrowThick}  />",
        "          <Slider   label=\"Arch\"      value={browArch}   onChange={setBrowArch}   />",
        "          <Slider   label=\"Length\"    value={browLength} onChange={setBrowLength} />",
        "          <ColorRow label=\"Color\"     value={browColor}  onChange={setBrowColor}  />",
        "        </>)}",
        "      </Section>",
        "      <Section title=\"✨ FX\" defaultOpen={false}>",
        "        <Check label=\"Glow Effect\"        value={glowEffect}  onChange={setGlowEffect}  />",
        "        {glowEffect && (<>",
        "          <ColorRow label=\"Glow Color\"    value={glowColor}     onChange={setGlowColor}     />",
        "          <Slider   label=\"Glow Intensity\" value={glowIntensity} onChange={setGlowIntensity} />",
        "        </>)}",
        "        <Check label=\"Cat-Eye Reflection\" value={catReflect} onChange={setCatReflect} />",
        "        <Check label=\"Scan Lines (Robot)\" value={scanLines}  onChange={setScanLines}  />",
        "      </Section>",
        "      <Section title=\"⚙ Output\" defaultOpen={false}>",
        "        <Select label=\"Poly Budget\"          value={polyBudget}   options={POLY_OPTIONS} onChange={setPolyBudget}   />",
        "        <Check  label=\"Generate Pair (L+R)\"  value={genPair}      onChange={setGenPair}      />",
        "        <Check  label=\"Heterochromia\"         value={heterochromia} onChange={setHeterochromia} />",
        "        {heterochromia && <ColorRow label=\"Right Eye Color\" value={rightColor} onChange={setRightColor} />}",
        "      </Section>",
        "      <GenBtn label=\"⚡ Generate Eye\" onClick={() => onGenerate?.({",
        "        eyeType, seed,",
        "        iris: { irisColor, irisColor2, irisPattern, irisRadius, irisDetail, irisFibril, irisRough, irisEmissive },",
        "        pupil: { pupilShape, pupilSize, pupilColor },",
        "        sclera: { scleraColor, scleraTint, bloodshot, scleraRough },",
        "        surface: { wetness, cornealBulge, reflectStr },",
        "        shape: { eyeSize, eyeDepth, eyeAngle, lidCrease, lidThick, lidColor },",
        "        lashes: { addLashes, lashDensity, lashLength, lashCurve, lashThick, lashColor },",
        "        brow: { addBrow, browThick, browArch, browLength, browColor },",
        "        fx: { glowEffect, glowColor, glowIntensity, catReflect, scanLines },",
        "        output: { polyBudget, genPair, heterochromia, rightColor },",
        "      })} />",
        "    </div>",
        "  );",
        "}",
    ]
    return lines

write(f"{BASE}/EyeGeneratorPanel.jsx", eye_panel())

# ── TeethGeneratorPanel ──────────────────────────────────────────────────────
def teeth_panel():
    lines = shared_ui()
    lines += [
        "const TEETH_TYPES  = ['Human Adult','Human Child','Vampire','Animal Canine','Animal Herbivore',",
        "  'Shark','Snake Fang','Robot','Cartoon','Zombie','Alien'];",
        "const GUM_SHAPES   = ['Normal','Receding','Inflamed','Healthy','Asymmetric','Exposed Root'];",
        "const POLY_OPTIONS = ['Low','Mid','High','Ultra'];",
        "",
        "/** TeethGeneratorPanel — full parametric teeth set with enamel, gums, wear, dental work */",
        "export default function TeethGeneratorPanel({ onGenerate }) {",
        "  const [teethType,     setTeethType]     = useState('Human Adult');",
        "  const [seed,          setSeed]          = useState(1);",
        "  const [incisorCount,  setIncisorCount]  = useState(4);",
        "  const [canineCount,   setCanineCount]   = useState(2);",
        "  const [premolarCount, setPremolarCount] = useState(4);",
        "  const [molarCount,    setMolarCount]    = useState(6);",
        "  const [showLower,     setShowLower]     = useState(true);",
        "  const [showWisdom,    setShowWisdom]    = useState(false);",
        "  const [toothSize,     setToothSize]     = useState(0.50);",
        "  const [toothWidth,    setToothWidth]    = useState(0.50);",
        "  const [toothHeight,   setToothHeight]   = useState(0.50);",
        "  const [incisorEdge,   setIncisorEdge]   = useState(0.50);",
        "  const [canineLen,     setCanineLen]     = useState(0.55);",
        "  const [spacing,       setSpacing]       = useState(0.50);",
        "  const [alignment,     setAlignment]     = useState(0.85);",
        "  const [overbite,      setOverbite]      = useState(0.20);",
        "  const [crowding,      setCrowding]      = useState(0.00);",
        "  const [rotation,      setRotation]      = useState(0.00);",
        "  const [enamelColor,   setEnamelColor]   = useState('#f5f0e0');",
        "  const [enamelRough,   setEnamelRough]   = useState(0.20);",
        "  const [enamelGloss,   setEnamelGloss]   = useState(0.75);",
        "  const [translucency,  setTranslucency]  = useState(0.30);",
        "  const [subsurface,    setSubsurface]    = useState(0.25);",
        "  const [stainLevel,    setStainLevel]    = useState(0.05);",
        "  const [stainColor,    setStainColor]    = useState('#c8b870');",
        "  const [wearLevel,     setWearLevel]     = useState(0.10);",
        "  const [crackDetail,   setCrackDetail]   = useState(0.00);",
        "  const [chipDetail,    setChipDetail]    = useState(0.00);",
        "  const [tartarLevel,   setTartarLevel]   = useState(0.00);",
        "  const [addGums,       setAddGums]       = useState(true);",
        "  const [gumShape,      setGumShape]      = useState('Normal');",
        "  const [gumColor,      setGumColor]      = useState('#c86070');",
        "  const [gumRecession,  setGumRecession]  = useState(0.10);",
        "  const [gumInflam,     setGumInflam]     = useState(0.00);",
        "  const [addBraces,     setAddBraces]     = useState(false);",
        "  const [bracesColor,   setBracesColor]   = useState('#aaaaaa');",
        "  const [addFillings,   setAddFillings]   = useState(false);",
        "  const [fillingsColor, setFillingsColor] = useState('#d0c8a0');",
        "  const [addCrowns,     setAddCrowns]     = useState(false);",
        "  const [addImplants,   setAddImplants]   = useState(false);",
        "  const [polyBudget,    setPolyBudget]    = useState('Mid');",
        "  const [separateMesh,  setSeparateMesh]  = useState(false);",
        "  const [addRoots,      setAddRoots]      = useState(false);",
        "",
        "  return (",
        "    <div style={P}>",
        "      <Section title=\"🦷 Teeth Type\">",
        "        <Badges items={TEETH_TYPES} active={teethType} onSelect={setTeethType} />",
        "        <Slider label=\"Random Seed\" value={seed} min={0} max={9999} step={1} onChange={setSeed} />",
        "      </Section>",
        "      <Section title=\"📊 Count & Layout\">",
        "        <Slider label=\"Incisors\"    value={incisorCount}  min={0} max={8}  step={1} onChange={setIncisorCount}  />",
        "        <Slider label=\"Canines\"     value={canineCount}   min={0} max={4}  step={1} onChange={setCanineCount}   />",
        "        <Slider label=\"Premolars\"   value={premolarCount} min={0} max={8}  step={1} onChange={setPremolarCount} />",
        "        <Slider label=\"Molars\"      value={molarCount}    min={0} max={12} step={1} onChange={setMolarCount}    />",
        "        <Check  label=\"Include Lower Jaw\" value={showLower}  onChange={setShowLower}  />",
        "        <Check  label=\"Wisdom Teeth\"      value={showWisdom} onChange={setShowWisdom} />",
        "      </Section>",
        "      <Section title=\"📐 Size & Shape\">",
        "        <Slider label=\"Overall Size\"    value={toothSize}   onChange={setToothSize}   />",
        "        <Slider label=\"Width\"           value={toothWidth}  onChange={setToothWidth}  />",
        "        <Slider label=\"Height\"          value={toothHeight} onChange={setToothHeight} />",
        "        <Slider label=\"Incisor Edge\"    value={incisorEdge} onChange={setIncisorEdge} />",
        "        <Slider label=\"Canine Length\"   value={canineLen}   onChange={setCanineLen}   />",
        "        <Slider label=\"Spacing\"         value={spacing}     onChange={setSpacing}     />",
        "        <Slider label=\"Alignment\"       value={alignment}   onChange={setAlignment}   />",
        "        <Slider label=\"Overbite\"        value={overbite}    onChange={setOverbite}    />",
        "        <Slider label=\"Crowding\"        value={crowding}    onChange={setCrowding}    />",
        "        <Slider label=\"Rotation\"        value={rotation}    onChange={setRotation}    />",
        "      </Section>",
        "      <Section title=\"✨ Enamel\">",
        "        <ColorRow label=\"Enamel Color\"  value={enamelColor}  onChange={setEnamelColor}  />",
        "        <Slider   label=\"Roughness\"     value={enamelRough}  onChange={setEnamelRough}  />",
        "        <Slider   label=\"Gloss\"         value={enamelGloss}  onChange={setEnamelGloss}  />",
        "        <Slider   label=\"Translucency\"  value={translucency} onChange={setTranslucency} />",
        "        <Slider   label=\"Subsurface\"    value={subsurface}   onChange={setSubsurface}   />",
        "      </Section>",
        "      <Section title=\"🎨 Stain & Wear\" defaultOpen={false}>",
        "        <Slider   label=\"Stain Level\"   value={stainLevel}   onChange={setStainLevel}   />",
        "        {stainLevel > 0 && <ColorRow label=\"Stain Color\" value={stainColor} onChange={setStainColor} />}",
        "        <Slider   label=\"Wear\"          value={wearLevel}    onChange={setWearLevel}    />",
        "        <Slider   label=\"Cracks\"        value={crackDetail}  onChange={setCrackDetail}  />",
        "        <Slider   label=\"Chips\"         value={chipDetail}   onChange={setChipDetail}   />",
        "        <Slider   label=\"Tartar\"        value={tartarLevel}  onChange={setTartarLevel}  />",
        "      </Section>",
        "      <Section title=\"🦀 Gums\" defaultOpen={false}>",
        "        <Check    label=\"Include Gums\"  value={addGums}      onChange={setAddGums}      />",
        "        {addGums && (<>",
        "          <Select   label=\"Gum Shape\"   value={gumShape}     options={GUM_SHAPES} onChange={setGumShape}     />",
        "          <ColorRow label=\"Gum Color\"   value={gumColor}     onChange={setGumColor}     />",
        "          <Slider   label=\"Recession\"   value={gumRecession} onChange={setGumRecession} />",
        "          <Slider   label=\"Inflammation\" value={gumInflam}   onChange={setGumInflam}    />",
        "        </>)}",
        "      </Section>",
        "      <Section title=\"🔧 Dental Work\" defaultOpen={false}>",
        "        <Check label=\"Braces\"    value={addBraces}  onChange={setAddBraces}  />",
        "        {addBraces && <ColorRow label=\"Braces Color\" value={bracesColor} onChange={setBracesColor} />}",
        "        <Check label=\"Fillings\"  value={addFillings} onChange={setAddFillings} />",
        "        {addFillings && <ColorRow label=\"Filling Color\" value={fillingsColor} onChange={setFillingsColor} />}",
        "        <Check label=\"Crowns\"    value={addCrowns}  onChange={setAddCrowns}  />",
        "        <Check label=\"Implants\"  value={addImplants} onChange={setAddImplants} />",
        "        <Check label=\"Show Roots\" value={addRoots}  onChange={setAddRoots}   />",
        "      </Section>",
        "      <Section title=\"⚙ Output\" defaultOpen={false}>",
        "        <Select label=\"Poly Budget\"     value={polyBudget}   options={POLY_OPTIONS} onChange={setPolyBudget}   />",
        "        <Check  label=\"Separate Meshes\" value={separateMesh} onChange={setSeparateMesh} />",
        "      </Section>",
        "      <GenBtn label=\"⚡ Generate Teeth\" onClick={() => onGenerate?.({",
        "        teethType, seed,",
        "        count: { incisorCount, canineCount, premolarCount, molarCount, showLower, showWisdom },",
        "        shape: { toothSize, toothWidth, toothHeight, incisorEdge, canineLen, spacing, alignment, overbite, crowding, rotation },",
        "        enamel: { enamelColor, enamelRough, enamelGloss, translucency, subsurface },",
        "        wear: { stainLevel, stainColor, wearLevel, crackDetail, chipDetail, tartarLevel },",
        "        gums: { addGums, gumShape, gumColor, gumRecession, gumInflam },",
        "        dental: { addBraces, bracesColor, addFillings, fillingsColor, addCrowns, addImplants, addRoots },",
        "        output: { polyBudget, separateMesh },",
        "      })} />",
        "    </div>",
        "  );",
        "}",
    ]
    return lines

write(f"{BASE}/TeethGeneratorPanel.jsx", teeth_panel())

# ── TattooGeneratorPanel ─────────────────────────────────────────────────────
def tattoo_panel():
    lines = shared_ui()
    lines += [
        "const TATTOO_STYLES = ['Traditional','Neo-Traditional','Realism','Tribal','Geometric',",
        "  'Watercolor','Japanese','Blackwork','Minimalist','Dotwork','Illustrative','Surrealism','Fine Line'];",
        "const BODY_REGIONS  = ['Upper Arm','Forearm','Full Sleeve','Chest','Back','Shoulder',",
        "  'Neck','Calf','Thigh','Full Leg','Hand','Foot','Spine','Rib','Hip','Wrist'];",
        "const SUBJECTS      = ['Custom','Floral','Animal','Portrait','Skull','Geometric',",
        "  'Script','Dragon','Phoenix','Koi','Samurai','Viking','Abstract','Mandala','Snake'];",
        "const POLY_OPTIONS  = ['Low','Mid','High'];",
        "",
        "/** TattooGeneratorPanel — procedural tattoo generator with style, aging, layout options */",
        "export default function TattooGeneratorPanel({ onGenerate }) {",
        "  const [tattooStyle,    setTattooStyle]    = useState('Traditional');",
        "  const [subject,        setSubject]        = useState('Floral');",
        "  const [bodyRegion,     setBodyRegion]     = useState('Upper Arm');",
        "  const [seed,           setSeed]           = useState(1);",
        "  const [inkColor,       setInkColor]       = useState('#1a1a2e');",
        "  const [inkColor2,      setInkColor2]      = useState('#8a2020');",
        "  const [inkColor3,      setInkColor3]      = useState('#204a8a');",
        "  const [inkColor4,      setInkColor4]      = useState('#208a40');",
        "  const [highlightColor, setHighlightColor] = useState('#e8e0c0');",
        "  const [colorCount,     setColorCount]     = useState(2);",
        "  const [scale,          setScale]          = useState(0.50);",
        "  const [positionX,      setPositionX]      = useState(0.50);",
        "  const [positionY,      setPositionY]      = useState(0.50);",
        "  const [rotation,       setRotation]       = useState(0.00);",
        "  const [opacity,        setOpacity]        = useState(0.95);",
        "  const [saturation,     setSaturation]     = useState(0.80);",
        "  const [contrast,       setContrast]       = useState(0.70);",
        "  const [lineWeight,     setLineWeight]     = useState(0.50);",
        "  const [shading,        setShading]        = useState(0.60);",
        "  const [highlight,      setHighlight]      = useState(0.40);",
        "  const [edgeSoftness,   setEdgeSoftness]   = useState(0.15);",
        "  const [detailLevel,    setDetailLevel]    = useState(0.70);",
        "  const [noiseTexture,   setNoiseTexture]   = useState(0.20);",
        "  const [inkSpread,      setInkSpread]      = useState(0.10);",
        "  const [aging,          setAging]          = useState(0.00);",
        "  const [fading,         setFading]         = useState(0.00);",
        "  const [blowout,        setBlowout]        = useState(0.00);",
        "  const [scarring,       setScarring]       = useState(0.00);",
        "  const [sunDamage,      setSunDamage]      = useState(0.00);",
        "  const [symmetry,       setSymmetry]       = useState(false);",
        "  const [mirrorX,        setMirrorX]        = useState(false);",
        "  const [tilePattern,    setTilePattern]    = useState(false);",
        "  const [wrapAround,     setWrapAround]     = useState(true);",
        "  const [followContour,  setFollowContour]  = useState(true);",
        "  const [procedural,     setProcedural]     = useState(false);",
        "  const [procDensity,    setProcDensity]    = useState(0.50);",
        "  const [procScale,      setProcScale]      = useState(0.50);",
        "  const [polyBudget,     setPolyBudget]     = useState('Mid');",
        "  const [exportUV,       setExportUV]       = useState(false);",
        "  const [exportMask,     setExportMask]     = useState(false);",
        "  const [exportAlpha,    setExportAlpha]    = useState(false);",
        "",
        "  return (",
        "    <div style={P}>",
        "      <Section title=\"🎨 Style & Subject\">",
        "        <Badges items={TATTOO_STYLES} active={tattooStyle} onSelect={setTattooStyle} />",
        "        <Select label=\"Subject\"     value={subject}    options={SUBJECTS}     onChange={setSubject}    />",
        "        <Select label=\"Body Region\" value={bodyRegion} options={BODY_REGIONS} onChange={setBodyRegion} />",
        "        <Slider label=\"Random Seed\" value={seed} min={0} max={9999} step={1} onChange={setSeed} />",
        "      </Section>",
        "      <Section title=\"🖌 Colors\">",
        "        <Slider label=\"Color Count\" value={colorCount} min={1} max={6} step={1} onChange={setColorCount} />",
        "        <ColorRow label=\"Ink 1\"       value={inkColor}       onChange={setInkColor}       />",
        "        {colorCount >= 2 && <ColorRow label=\"Ink 2\" value={inkColor2} onChange={setInkColor2} />}",
        "        {colorCount >= 3 && <ColorRow label=\"Ink 3\" value={inkColor3} onChange={setInkColor3} />}",
        "        {colorCount >= 4 && <ColorRow label=\"Ink 4\" value={inkColor4} onChange={setInkColor4} />}",
        "        <ColorRow label=\"Highlight\"   value={highlightColor} onChange={setHighlightColor} />",
        "      </Section>",
        "      <Section title=\"📏 Placement\">",
        "        <Slider label=\"Scale\"      value={scale}     onChange={setScale}     />",
        "        <Slider label=\"Position X\" value={positionX} onChange={setPositionX} />",
        "        <Slider label=\"Position Y\" value={positionY} onChange={setPositionY} />",
        "        <Slider label=\"Rotation\"   value={rotation}  min={-1} max={1} step={0.01} onChange={setRotation} />",
        "      </Section>",
        "      <Section title=\"✒ Ink Properties\">",
        "        <Slider label=\"Opacity\"     value={opacity}    onChange={setOpacity}    />",
        "        <Slider label=\"Saturation\"  value={saturation} onChange={setSaturation} />",
        "        <Slider label=\"Contrast\"    value={contrast}   onChange={setContrast}   />",
        "        <Slider label=\"Line Weight\" value={lineWeight} onChange={setLineWeight} />",
        "        <Slider label=\"Shading\"     value={shading}    onChange={setShading}    />",
        "        <Slider label=\"Highlight\"   value={highlight}  onChange={setHighlight}  />",
        "        <Slider label=\"Edge Softness\" value={edgeSoftness} onChange={setEdgeSoftness} />",
        "        <Slider label=\"Detail\"      value={detailLevel}  onChange={setDetailLevel}  />",
        "        <Slider label=\"Noise\"       value={noiseTexture} onChange={setNoiseTexture} />",
        "        <Slider label=\"Ink Spread\"  value={inkSpread}    onChange={setInkSpread}    />",
        "      </Section>",
        "      <Section title=\"⏳ Aging & Wear\" defaultOpen={false}>",
        "        <Slider label=\"Age\"        value={aging}     onChange={setAging}     />",
        "        <Slider label=\"Fading\"     value={fading}    onChange={setFading}    />",
        "        <Slider label=\"Blowout\"    value={blowout}   onChange={setBlowout}   />",
        "        <Slider label=\"Scarring\"   value={scarring}  onChange={setScarring}  />",
        "        <Slider label=\"Sun Damage\" value={sunDamage} onChange={setSunDamage} />",
        "      </Section>",
        "      <Section title=\"🔲 Layout\" defaultOpen={false}>",
        "        <Check label=\"Symmetry\"       value={symmetry}      onChange={setSymmetry}      />",
        "        <Check label=\"Mirror X\"       value={mirrorX}       onChange={setMirrorX}       />",
        "        <Check label=\"Tile Pattern\"   value={tilePattern}   onChange={setTilePattern}   />",
        "        <Check label=\"Wrap Around\"    value={wrapAround}    onChange={setWrapAround}    />",
        "        <Check label=\"Follow Contour\" value={followContour} onChange={setFollowContour} />",
        "      </Section>",
        "      <Section title=\"🤖 Procedural\" defaultOpen={false}>",
        "        <Check label=\"Procedural Mode\" value={procedural} onChange={setProcedural} />",
        "        {procedural && (<>",
        "          <Slider label=\"Density\" value={procDensity} onChange={setProcDensity} />",
        "          <Slider label=\"Scale\"   value={procScale}   onChange={setProcScale}   />",
        "        </>)}",
        "      </Section>",
        "      <Section title=\"⚙ Output\" defaultOpen={false}>",
        "        <Select label=\"Poly Budget\"  value={polyBudget}  options={POLY_OPTIONS} onChange={setPolyBudget}  />",
        "        <Check  label=\"Export UV Map\"  value={exportUV}    onChange={setExportUV}    />",
        "        <Check  label=\"Export Mask\"    value={exportMask}  onChange={setExportMask}  />",
        "        <Check  label=\"Export Alpha\"   value={exportAlpha} onChange={setExportAlpha} />",
        "      </Section>",
        "      <GenBtn label=\"⚡ Generate Tattoo\" onClick={() => onGenerate?.({",
        "        tattooStyle, subject, bodyRegion, seed,",
        "        colors: { inkColor, inkColor2, inkColor3, inkColor4, highlightColor, colorCount },",
        "        placement: { scale, positionX, positionY, rotation },",
        "        ink: { opacity, saturation, contrast, lineWeight, shading, highlight, edgeSoftness, detailLevel, noiseTexture, inkSpread },",
        "        aging: { aging, fading, blowout, scarring, sunDamage },",
        "        layout: { symmetry, mirrorX, tilePattern, wrapAround, followContour },",
        "        procedural: { procedural, procDensity, procScale },",
        "        output: { polyBudget, exportUV, exportMask, exportAlpha },",
        "      })} />",
        "    </div>",
        "  );",
        "}",
    ]
    return lines

write(f"{BASE}/TattooGeneratorPanel.jsx", tattoo_panel())

# ── BodyGeneratorPanel ───────────────────────────────────────────────────────
def body_panel():
    lines = shared_ui()
    lines += [
        "const GENDERS      = ['Male','Female','Non-Binary','Androgynous','Masculine','Feminine'];",
        "const BODY_TYPES   = ['Ectomorph','Slim','Lean','Athletic','Average','Stocky','Endomorph','Mesomorph'];",
        "const AGE_GROUPS   = ['Child (6-12)','Teen (13-17)','Young Adult (18-25)','Adult (26-40)','Middle-Aged (41-60)','Senior (60+)'];",
        "const SKIN_TONES   = ['#f5d0b0','#e8b68a','#c8906a','#a0663a','#7a4420','#4a2210','#d0b090','#b89070'];",
        "const POLY_OPTIONS = ['Low','Mid','High','Ultra'];",
        "",
        "/** BodyGeneratorPanel — full-body parametric generator with 20+ proportion sliders */",
        "export default function BodyGeneratorPanel({ onGenerate }) {",
        "  const [gender,         setGender]         = useState('Male');",
        "  const [bodyType,       setBodyType]       = useState('Average');",
        "  const [ageGroup,       setAgeGroup]       = useState('Adult (26-40)');",
        "  const [seed,           setSeed]           = useState(1);",
        "  const [height,         setHeight]         = useState(175);",
        "  const [weight,         setWeight]         = useState(75);",
        "  const [muscleDef,      setMuscleDef]      = useState(0.50);",
        "  const [bodyFat,        setBodyFat]        = useState(0.18);",
        "  const [boneFrame,      setBoneFrame]      = useState(0.50);",
        "  const [waterRetention, setWaterRetention] = useState(0.40);",
        "  const [shoulderW,      setShoulderW]      = useState(0.50);",
        "  const [chestSize,      setChestSize]      = useState(0.50);",
        "  const [chestDepth,     setChestDepth]     = useState(0.45);",
        "  const [neckThick,      setNeckThick]      = useState(0.45);",
        "  const [armLen,         setArmLen]         = useState(0.50);",
        "  const [upperArmThick,  setUpperArmThick]  = useState(0.45);",
        "  const [forearmThick,   setForearmThick]   = useState(0.42);",
        "  const [wristSize,      setWristSize]      = useState(0.38);",
        "  const [handSize,       setHandSize]       = useState(0.48);",
        "  const [waistSize,      setWaistSize]      = useState(0.42);",
        "  const [abDef,          setAbDef]          = useState(0.40);",
        "  const [loveHandles,    setLoveHandles]    = useState(0.15);",
        "  const [hipSize,        setHipSize]        = useState(0.50);",
        "  const [gluteSize,      setGluteSize]      = useState(0.50);",
        "  const [legLen,         setLegLen]         = useState(0.50);",
        "  const [thighThick,     setThighThick]     = useState(0.48);",
        "  const [calfSize,       setCalfSize]       = useState(0.44);",
        "  const [ankleSize,      setAnkleSize]      = useState(0.36);",
        "  const [footSize,       setFootSize]       = useState(0.50);",
        "  const [skinTone,       setSkinTone]       = useState('#c8906a');",
        "  const [skinRough,      setSkinRough]      = useState(0.55);",
        "  const [skinGloss,      setSkinGloss]      = useState(0.25);",
        "  const [subsurface,     setSubsurface]     = useState(0.60);",
        "  const [polyBudget,     setPolyBudget]     = useState('High');",
        "  const [addRig,         setAddRig]         = useState(true);",
        "  const [addLOD,         setAddLOD]         = useState(false);",
        "  const [separateHead,   setSeparateHead]   = useState(false);",
        "  const [addSubdiv,      setAddSubdiv]      = useState(false);",
        "",
        "  const randomize = useCallback(() => {",
        "    const rn = (a,b) => parseFloat((a+Math.random()*(b-a)).toFixed(2));",
        "    const pick = arr => arr[Math.floor(Math.random()*arr.length)];",
        "    setGender(pick(GENDERS)); setBodyType(pick(BODY_TYPES));",
        "    setHeight(Math.round(150+Math.random()*60));",
        "    setWeight(Math.round(50+Math.random()*80));",
        "    setMuscleDef(rn(0,1)); setBodyFat(rn(0.05,0.45));",
        "    setShoulderW(rn(0.3,0.75)); setHipSize(rn(0.3,0.72));",
        "  }, []);",
        "",
        "  return (",
        "    <div style={P}>",
        "      <Section title=\"🧬 Base\">",
        "        <Badges items={GENDERS}   active={gender}   onSelect={setGender}   />",
        "        <Select label=\"Body Type\" value={bodyType}  options={BODY_TYPES}   onChange={setBodyType}  />",
        "        <Select label=\"Age Group\" value={ageGroup}  options={AGE_GROUPS}   onChange={setAgeGroup}  />",
        "        <Slider label=\"Seed\"      value={seed} min={0} max={9999} step={1} onChange={setSeed} />",
        "      </Section>",
        "      <Section title=\"📏 Scale\">",
        "        <NumInput label=\"Height\" value={height} min={120} max={230} step={1} onChange={setHeight} unit=\"cm\" />",
        "        <NumInput label=\"Weight\" value={weight} min={35}  max={200} step={1} onChange={setWeight} unit=\"kg\" />",
        "      </Section>",
        "      <Section title=\"💪 Composition\">",
        "        <Slider label=\"Muscle Definition\" value={muscleDef}      onChange={setMuscleDef}      />",
        "        <Slider label=\"Body Fat %\"        value={bodyFat}        onChange={setBodyFat}        />",
        "        <Slider label=\"Bone Frame\"        value={boneFrame}      onChange={setBoneFrame}      />",
        "        <Slider label=\"Water Retention\"   value={waterRetention} onChange={setWaterRetention} />",
        "      </Section>",
        "      <Section title=\"💪 Upper Body\">",
        "        <Slider label=\"Shoulder Width\"  value={shoulderW}    onChange={setShoulderW}    />",
        "        <Slider label=\"Chest Size\"      value={chestSize}    onChange={setChestSize}    />",
        "        <Slider label=\"Chest Depth\"     value={chestDepth}   onChange={setChestDepth}   />",
        "        <Slider label=\"Neck Thickness\"  value={neckThick}    onChange={setNeckThick}    />",
        "        <Slider label=\"Arm Length\"      value={armLen}       onChange={setArmLen}       />",
        "        <Slider label=\"Upper Arm\"       value={upperArmThick} onChange={setUpperArmThick} />",
        "        <Slider label=\"Forearm\"         value={forearmThick} onChange={setForearmThick} />",
        "        <Slider label=\"Wrist\"           value={wristSize}    onChange={setWristSize}    />",
        "        <Slider label=\"Hand Size\"       value={handSize}     onChange={setHandSize}     />",
        "      </Section>",
        "      <Section title=\"🫃 Core\">",
        "        <Slider label=\"Waist Size\"    value={waistSize}   onChange={setWaistSize}   />",
        "        <Slider label=\"Ab Definition\" value={abDef}       onChange={setAbDef}       />",
        "        <Slider label=\"Love Handles\"  value={loveHandles} onChange={setLoveHandles} />",
        "        <Slider label=\"Hip Size\"      value={hipSize}     onChange={setHipSize}     />",
        "        <Slider label=\"Glute Size\"    value={gluteSize}   onChange={setGluteSize}   />",
        "      </Section>",
        "      <Section title=\"🦵 Lower Body\">",
        "        <Slider label=\"Leg Length\"  value={legLen}     onChange={setLegLen}     />",
        "        <Slider label=\"Thigh\"       value={thighThick} onChange={setThighThick} />",
        "        <Slider label=\"Calf\"        value={calfSize}   onChange={setCalfSize}   />",
        "        <Slider label=\"Ankle\"       value={ankleSize}  onChange={setAnkleSize}  />",
        "        <Slider label=\"Foot Size\"   value={footSize}   onChange={setFootSize}   />",
        "      </Section>",
        "      <Section title=\"🎨 Skin\" defaultOpen={false}>",
        "        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 6 }}>",
        "          {SKIN_TONES.map(t => (",
        "            <div key={t} onClick={() => setSkinTone(t)} style={{",
        "              width: 24, height: 24, borderRadius: 4, background: t, cursor: 'pointer',",
        "              border: `2px solid ${skinTone === t ? '#00ffc8' : '#21262d'}`,",
        "            }} />",
        "          ))}",
        "        </div>",
        "        <ColorRow label=\"Custom Tone\" value={skinTone}   onChange={setSkinTone}   />",
        "        <Slider   label=\"Roughness\"   value={skinRough}  onChange={setSkinRough}  />",
        "        <Slider   label=\"Gloss\"       value={skinGloss}  onChange={setSkinGloss}  />",
        "        <Slider   label=\"Subsurface\"  value={subsurface} onChange={setSubsurface} />",
        "      </Section>",
        "      <Section title=\"⚙ Output\" defaultOpen={false}>",
        "        <Select label=\"Poly Budget\"   value={polyBudget}   options={POLY_OPTIONS} onChange={setPolyBudget}   />",
        "        <Check  label=\"Add Rig\"       value={addRig}       onChange={setAddRig}       />",
        "        <Check  label=\"Auto LOD\"      value={addLOD}       onChange={setAddLOD}       />",
        "        <Check  label=\"Separate Head\" value={separateHead} onChange={setSeparateHead} />",
        "        <Check  label=\"Subdivision\"   value={addSubdiv}    onChange={setAddSubdiv}    />",
        "      </Section>",
        "      <div style={{ display: 'flex', gap: 6 }}>",
        "        <button onClick={randomize} style={{",
        "          background: '#1a1f2c', color: '#888', border: '1px solid #21262d',",
        "          borderRadius: 4, padding: '6px 10px', cursor: 'pointer', fontSize: 11,",
        "        }}>🎲</button>",
        "        <GenBtn label=\"⚡ Generate Body\" onClick={() => onGenerate?.({",
        "          gender, bodyType, ageGroup, seed, height, weight,",
        "          composition: { muscleDef, bodyFat, boneFrame, waterRetention },",
        "          upper: { shoulderW, chestSize, chestDepth, neckThick, armLen, upperArmThick, forearmThick, wristSize, handSize },",
        "          core: { waistSize, abDef, loveHandles, hipSize, gluteSize },",
        "          lower: { legLen, thighThick, calfSize, ankleSize, footSize },",
        "          skin: { skinTone, skinRough, skinGloss, subsurface },",
        "          output: { polyBudget, addRig, addLOD, separateHead, addSubdiv },",
        "        })} />",
        "      </div>",
        "    </div>",
        "  );",
        "}",
    ]
    return lines

write(f"{BASE}/BodyGeneratorPanel.jsx", body_panel())

print("\n✅ Script 1/4 complete — all 6 files written.")
