from pathlib import Path
import re

app = Path("/workspaces/spx-mesh-editor/src/App.jsx")
src = app.read_text()
original_len = len(src.splitlines())

# ── 1. State vars ─────────────────────────────────────────────────────────────
old_state = "  const [showProbePanel, setShowProbePanel] = useState(false);"
new_state = (
    "  const [showProbePanel, setShowProbePanel] = useState(false);\n"
    "  const [showUDIMPanel, setShowUDIMPanel] = useState(false);\n"
    "  const [udimLayout, setUdimLayout] = useState(null);\n"
    "  const [udimTileCount, setUdimTileCount] = useState(4);\n"
    "  const [udimActiveTile, setUdimActiveTile] = useState(1001);\n"
    "  const [udimPaintColor, setUdimPaintColor] = useState('#00ffc8');\n"
    "  const [giResolution, setGiResolution] = useState(256);\n"
    "  const [giProbes, setGiProbes] = useState([]);\n"
    "  const [giBaked, setGiBaked] = useState(false);"
)
src = src.replace(old_state, new_state, 1)

# ── 2. Handlers ───────────────────────────────────────────────────────────────
old_handler = "  // ── Sessions 108-121: VFX + Fluid + Asset + Procedural state ─────────────"
new_handler = (
    "  // ── Session D: GI + UDIM handlers ──────────────────────────────────────\n"
    "  const handleBakeGI = useCallback(() => {\n"
    "    const renderer = rendererRef.current;\n"
    "    const scene    = sceneRef.current;\n"
    "    const camera   = cameraRef.current;\n"
    "    if (!renderer || !scene || !camera) { setStatus('No renderer'); return; }\n"
    "    setStatus('Baking GI...');\n"
    "    const envMap = bakeEnvironment(renderer, scene, camera, { resolution: giResolution });\n"
    "    if (envMap) {\n"
    "      applyIBLToScene(scene, envMap, { intensity: 1.0, background: false });\n"
    "      const probe = createIrradianceProbe(new THREE.Vector3(0,0,0), { resolution: giResolution });\n"
    "      setGiProbes(p => [...p, probe]);\n"
    "      setGiBaked(true);\n"
    "      setStatus('GI baked');\n"
    "    } else { setStatus('GI bake failed'); }\n"
    "  }, [giResolution]);\n"
    "\n"
    "  const handleCreateReflectionProbe = useCallback(() => {\n"
    "    const renderer = rendererRef.current;\n"
    "    const scene    = sceneRef.current;\n"
    "    const camera   = cameraRef.current;\n"
    "    if (!renderer || !scene || !camera) return;\n"
    "    const probe = createReflectionProbe(new THREE.Vector3(0,1,0), { resolution: giResolution });\n"
    "    updateReflectionProbe(probe, renderer, scene);\n"
    "    applyProbeToScene(scene, probe);\n"
    "    setGiProbes(p => [...p, probe]);\n"
    "    setStatus('Reflection probe created');\n"
    "  }, [giResolution]);\n"
    "\n"
    "  const handleInitUDIM = useCallback(() => {\n"
    "    const layout = createUDIMLayout(udimTileCount);\n"
    "    initUDIMLayout(layout, 1024, 1024);\n"
    "    setUdimLayout(layout);\n"
    "    setStatus('UDIM initialized: ' + udimTileCount + ' tiles');\n"
    "  }, [udimTileCount]);\n"
    "\n"
    "  const handleFillUDIMTile = useCallback(() => {\n"
    "    if (!udimLayout) { setStatus('Init UDIM first'); return; }\n"
    "    fillUDIMTile(udimLayout, udimActiveTile, udimPaintColor);\n"
    "    setUdimLayout({ ...udimLayout });\n"
    "    setStatus('Filled tile ' + udimActiveTile);\n"
    "  }, [udimLayout, udimActiveTile, udimPaintColor]);\n"
    "\n"
    "  const handleExportUDIMAtlas = useCallback(() => {\n"
    "    if (!udimLayout) { setStatus('Init UDIM first'); return; }\n"
    "    const atlas = buildUDIMAtlas(udimLayout, 4096, 4096);\n"
    "    const url   = atlas.canvas.toDataURL('image/png');\n"
    "    const a     = document.createElement('a');\n"
    "    a.href = url; a.download = 'udim_atlas.png'; a.click();\n"
    "    setStatus('UDIM atlas exported');\n"
    "  }, [udimLayout]);\n"
    "\n"
    "  const handleApplyUDIMToMesh = useCallback(() => {\n"
    "    const mesh = meshRef.current;\n"
    "    if (!mesh || !udimLayout) { setStatus('Need mesh + UDIM layout'); return; }\n"
    "    applyUDIMToMaterial(mesh.material, udimLayout);\n"
    "    setStatus('UDIM applied to mesh');\n"
    "  }, [udimLayout]);\n"
    "  // ── Session D END ─────────────────────────────────────────────────────\n"
    "  // ── Sessions 108-121: VFX + Fluid + Asset + Procedural state ─────────────"
)
src = src.replace(old_handler, new_handler, 1)

# ── 3. Expand probe panel to include GI baking ───────────────────────────────
old_probe_open = "            {showProbePanel && ("
new_probe_open = (
    "            {showProbePanel && (\n"
    "              <div style={{padding:'8px 0',borderBottom:'1px solid #21262d',marginBottom:6}}>\n"
    "                <div style={{color:'#00ffc8',fontSize:9,fontWeight:700,marginBottom:6}}>GI / ENVIRONMENT PROBES</div>\n"
    "                <div style={{marginBottom:4}}>\n"
    "                  <span style={{color:'#888',fontSize:8}}>Bake Resolution</span>\n"
    "                  <select value={giResolution} onChange={e=>setGiResolution(Number(e.target.value))}\n"
    "                    style={{width:'100%',background:'#0d1117',border:'1px solid #21262d',color:'#dde6ef',fontSize:8,padding:2,marginTop:2}}>\n"
    "                    <option value={64}>64 (fast)</option>\n"
    "                    <option value={128}>128</option>\n"
    "                    <option value={256}>256 (default)</option>\n"
    "                    <option value={512}>512 (high)</option>\n"
    "                  </select>\n"
    "                </div>\n"
    "                <button onClick={handleBakeGI} style={{width:'100%',padding:'4px',\n"
    "                  background:giBaked?'#003322':'#1a1f2e',\n"
    "                  border:'1px solid '+(giBaked?'#00ffc8':'#21262d'),\n"
    "                  color:giBaked?'#00ffc8':'#aaa',borderRadius:3,cursor:'pointer',fontSize:8,marginBottom:3}}>\n"
    "                  {giBaked ? 'Rebake GI' : 'Bake GI Probe'}\n"
    "                </button>\n"
    "                <button onClick={handleCreateReflectionProbe} style={{width:'100%',padding:'4px',\n"
    "                  background:'#1a1f2e',border:'1px solid #21262d',color:'#aaa',\n"
    "                  borderRadius:3,cursor:'pointer',fontSize:8,marginBottom:3}}>\n"
    "                  Add Reflection Probe\n"
    "                </button>\n"
    "                <div style={{color:'#555',fontSize:7}}>Probes: {giProbes.length}</div>\n"
    "              </div>\n"
    "            )}\n"
    "            {showProbePanel && ("
)
src = src.replace(old_probe_open, new_probe_open, 1)

# ── 4. UDIM panel — inject before the render panel group ─────────────────────
old_render_group = "      {(showRenderPanel || showVolPanel || showPassPanel || showProbePanel) && ("
udim_panel = (
    "      {showUDIMPanel && (\n"
    "        <div style={{position:'fixed',top:40,right:220,width:200,background:'#0d1117',\n"
    "          border:'1px solid #21262d',borderRadius:4,padding:8,zIndex:100,overflowY:'auto',maxHeight:'70vh'}}>\n"
    "          <div style={{color:'#00ffc8',fontSize:9,fontWeight:700,marginBottom:6}}>UDIM TEXTURES</div>\n"
    "          <div style={{marginBottom:4}}>\n"
    "            <span style={{color:'#888',fontSize:8}}>Tile Count</span>\n"
    "            <select value={udimTileCount} onChange={e=>setUdimTileCount(Number(e.target.value))}\n"
    "              style={{width:'100%',background:'#0d1117',border:'1px solid #21262d',color:'#dde6ef',fontSize:8,padding:2,marginTop:2}}>\n"
    "              {[1,2,4,6,8,10,16,20].map(n=><option key={n} value={n}>{n} tile{n>1?'s':''}</option>)}\n"
    "            </select>\n"
    "          </div>\n"
    "          <button onClick={handleInitUDIM} style={{width:'100%',padding:'4px',\n"
    "            background:udimLayout?'#003322':'#1a1f2e',\n"
    "            border:'1px solid '+(udimLayout?'#00ffc8':'#21262d'),\n"
    "            color:udimLayout?'#00ffc8':'#aaa',borderRadius:3,cursor:'pointer',fontSize:8,marginBottom:3}}>\n"
    "            {udimLayout ? 'Re-Init Layout' : 'Init UDIM Layout'}\n"
    "          </button>\n"
    "          {udimLayout && (<>\n"
    "            <div style={{marginBottom:4}}>\n"
    "              <span style={{color:'#888',fontSize:8}}>Active Tile</span>\n"
    "              <select value={udimActiveTile} onChange={e=>setUdimActiveTile(Number(e.target.value))}\n"
    "                style={{width:'100%',background:'#0d1117',border:'1px solid #21262d',color:'#dde6ef',fontSize:8,padding:2,marginTop:2}}>\n"
    "                {udimLayout.tiles.map(t=><option key={t.id} value={t.id}>UDIM {t.id}</option>)}\n"
    "              </select>\n"
    "            </div>\n"
    "            <div style={{marginBottom:4}}>\n"
    "              <span style={{color:'#888',fontSize:8}}>Paint Color</span>\n"
    "              <input type='color' value={udimPaintColor} onChange={e=>setUdimPaintColor(e.target.value)}\n"
    "                style={{width:'100%',height:24,border:'none',background:'none',cursor:'pointer',marginTop:2}} />\n"
    "            </div>\n"
    "            <button onClick={handleFillUDIMTile} style={{width:'100%',padding:'4px',background:'#1a1f2e',\n"
    "              border:'1px solid #21262d',color:'#aaa',borderRadius:3,cursor:'pointer',fontSize:8,marginBottom:3}}>\n"
    "              Fill Active Tile\n"
    "            </button>\n"
    "            <button onClick={handleApplyUDIMToMesh} style={{width:'100%',padding:'4px',background:'#1a1f2e',\n"
    "              border:'1px solid #21262d',color:'#aaa',borderRadius:3,cursor:'pointer',fontSize:8,marginBottom:3}}>\n"
    "              Apply to Mesh\n"
    "            </button>\n"
    "            <button onClick={handleExportUDIMAtlas} style={{width:'100%',padding:'4px',background:'#1a1f2e',\n"
    "              border:'1px solid #21262d',color:'#FF6600',borderRadius:3,cursor:'pointer',fontSize:8,marginBottom:3}}>\n"
    "              Export Atlas 4096px\n"
    "            </button>\n"
    "            <div style={{color:'#555',fontSize:7}}>Tiles: {getUDIMStats(udimLayout).initialized}/{getUDIMStats(udimLayout).tiles}</div>\n"
    "          </>)}\n"
    "        </div>\n"
    "      )}\n"
    "      {(showRenderPanel || showVolPanel || showPassPanel || showProbePanel) && ("
)
src = src.replace(old_render_group, udim_panel, 1)

app.write_text(src)
new_len = len(src.splitlines())
print(f"Done. {original_len} -> {new_len} lines (+{new_len - original_len})")
