export const COMPOSITOR_NODE_TYPES={INPUT:["RenderLayer","Image","Texture","Value","RGB"],OUTPUT:["Composite","Viewer","FileOutput"],COLOR:["AlphaOver","BrightContrast","ColorBalance","HueSat","Mix","Invert","Gamma","Tonemap"],FILTER:["Blur","Glare","Bokeh","Sharpen","Denoise"],MATTE:["AlphaConvert","SetAlpha","IDMask"],TRANSFORM:["Scale","Transform","Rotate","Flip"],UTILITIES:["Math","SeparateRGBA","CombineRGBA"]};
function buildInputs(type){const m={Mix:[{name:"Fac",type:"value"},{name:"Image1",type:"image"},{name:"Image2",type:"image"}],Blur:[{name:"Image",type:"image"},{name:"Size",type:"value"}],AlphaOver:[{name:"Fac",type:"value"},{name:"Image1",type:"image"},{name:"Image2",type:"image"}],BrightContrast:[{name:"Image",type:"image"},{name:"Bright",type:"value"},{name:"Contrast",type:"value"}],Glare:[{name:"Image",type:"image"}],Denoise:[{name:"Image",type:"image"},{name:"Normal",type:"image"},{name:"Albedo",type:"image"}],ColorBalance:[{name:"Fac",type:"value"},{name:"Image",type:"image"}],HueSat:[{name:"Hue",type:"value"},{name:"Sat",type:"value"},{name:"Val",type:"value"},{name:"Image",type:"image"}],Composite:[{name:"Image",type:"image"},{name:"Alpha",type:"value"}],Viewer:[{name:"Image",type:"image"}]};return(m[type]||[{name:"Image",type:"image"}]).map(i=>({...i,id:crypto.randomUUID(),connected:null}));}
function buildOutputs(type){const m={RenderLayer:[{name:"Image"},{name:"Alpha"},{name:"Z"},{name:"Normal"},{name:"Diffuse"}],Mix:[{name:"Image"}],Blur:[{name:"Image"}],Glare:[{name:"Image"}],Denoise:[{name:"Image"}],Composite:[]};return(m[type]||[{name:"Image"}]).map(o=>({...o,id:crypto.randomUUID(),type:"image"}));}
function buildParams(type,overrides={}){const d={Mix:{blendType:"MIX",use_alpha:false},Blur:{sizeX:3,sizeY:3,filterType:"GAUSS"},Glare:{glareType:"BLOOM",quality:"MEDIUM",threshold:1.0,size:8},BrightContrast:{bright:0,contrast:0},HueSat:{hue:0.5,saturation:1,value:1},ColorBalance:{lift:[1,1,1],gamma:[1,1,1],gain:[1,1,1]},Denoise:{use_hdr:false}};return{...(d[type]||{}),...overrides};}
export function createCompositorNode(type,opts={}){return{id:crypto.randomUUID(),type,label:opts.label||type,position:opts.position||{x:0,y:0},inputs:buildInputs(type),outputs:buildOutputs(type),params:buildParams(type,opts.params||{}),mute:false,preview:null};}
export function createCompositorGraph(){return{id:crypto.randomUUID(),nodes:[],connections:[],active:true};}
export function addCompositorNode(graph,type,opts={}){const node=createCompositorNode(type,opts);graph.nodes.push(node);return node;}
export function connectCompositorNodes(graph,fromNodeId,fromOutput,toNodeId,toInput){const conn={id:crypto.randomUUID(),fromNodeId,fromOutput,toNodeId,toInput};graph.connections.push(conn);const toNode=graph.nodes.find(n=>n.id===toNodeId);if(toNode){const inp=toNode.inputs.find(i=>i.name===toInput);if(inp)inp.connected=conn.id;}return conn;}
export function removeCompositorNode(graph,id){graph.nodes=graph.nodes.filter(n=>n.id!==id);graph.connections=graph.connections.filter(c=>c.fromNodeId!==id&&c.toNodeId!==id);return graph;}
export function evaluateCompositorGraph(graph){const composite=graph.nodes.find(n=>n.type==="Composite");if(!composite)return null;const input=graph.connections.find(c=>c.toNodeId===composite.id&&c.toInput==="Image");return{evaluated:true,outputNode:composite.id,inputConnection:input};}
export function getCompositorStats(graph){return{nodes:graph.nodes.length,connections:graph.connections.length,active:graph.active};}
export const COMPOSITOR_PRESETS={};
export function applyCompositorPreset(name){const graph=createCompositorGraph();const presets={bloom:(g)=>{const rl=addCompositorNode(g,"RenderLayer",{position:{x:0,y:0}});const gl=addCompositorNode(g,"Glare",{position:{x:200,y:0}});const mx=addCompositorNode(g,"Mix",{position:{x:400,y:0},params:{blendType:"ADD"}});const out=addCompositorNode(g,"Composite",{position:{x:600,y:0}});connectCompositorNodes(g,rl.id,"Image",gl.id,"Image");connectCompositorNodes(g,rl.id,"Image",mx.id,"Image1");connectCompositorNodes(g,gl.id,"Image",mx.id,"Image2");connectCompositorNodes(g,mx.id,"Image",out.id,"Image");return g;},denoise:(g)=>{const rl=addCompositorNode(g,"RenderLayer",{position:{x:0,y:0}});const dn=addCompositorNode(g,"Denoise",{position:{x:200,y:0}});const out=addCompositorNode(g,"Composite",{position:{x:400,y:0}});connectCompositorNodes(g,rl.id,"Image",dn.id,"Image");connectCompositorNodes(g,rl.id,"Normal",dn.id,"Normal");connectCompositorNodes(g,rl.id,"Diffuse",dn.id,"Albedo");connectCompositorNodes(g,dn.id,"Image",out.id,"Image");return g;}};const fn=presets[name];if(fn)fn(graph);return graph;}
